version: '2'
services:
    php7:
        image: lxmltj/php7
        volumes:
            - ./crm:/var/www/html
            - ./dockers/log:/var/log/apache2
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
        ports:
            - 5066:80
        links:
            - database:db

    database:
        image: mysql:5.7
        restart: always
        volumes:
            - ./dockers/database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=12345

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - database:db
        ports:
            - 8181:80
        environment:
            - PMA_USER=root
            - PMA_PASSWORD=12345